### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by armstrong1972** [Eusth/IPA#1]
ProgramTest.cs :
        public void CopiesCorrectly(string from, string to, string nativeFolder, bool isFlat, string[] expected)
        {
            var outcome = Program.NativePluginInterceptor(new FileInfo(from), new FileInfo(to), new DirectoryInfo(nativeFolder), isFlat).Select(f => f.FullName).ToList();

            var expectedPaths = expected.Select(e => new FileInfo(e)).Select(f => f.FullName).ToList();
            Assert.Equal(expectedPaths, outcome);
        }

There is no last param "Architecture" to call NativePluginInterceptor function , it can't compile.

**Comment by Eusth** [comment]
Fixed it at last.
