### ISSUE TITLE
Crashes when I drag any .EXE onto it

### ISSUE THREAD

**Issue by frank21347** [Eusth/IPA#3]
I have followed 2 image tutorials, and 1 YouTube tutorial, and despite doing every step those people are doing when I drag an .EXE onto IPA.exe it just opens and crashes. No error message is given at all?? If I run it from a console window it says this:

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or ass
embly 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c56193
4e089' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Core, Version=3.5.0.0, Culture=neutral, PublicKeyToken=b77a5c
561934e089'
   at IPA.Program.Main(String[] args)

**Comment by hyryel** [comment]
Hi, it seems you lack the .Net Framework 3.5.
If you are using Windows 10, follow this link : [How to install .Net 3.5 for Windows 10](https://docs.microsoft.com/en-us/dotnet/framework/install/dotnet-35-windows-10)

Tell me if this solve your issue.

**Comment by frank21347** [comment]
I am on Windows 7. I just had to check the box for it in my Control Panel -> Programs & Features -> Turn Windows Features On or Off. Once I installed it from there and rebooted it worked fine!

**Comment by hyryel** [comment]
Glad I could Help. Enjoy your game.
