### ISSUE TITLE
Cannot patch UnityEngine.dll

### ISSUE THREAD

**Issue by russianGecko** [Eusth/IPA#4]
It seems Unity moved to a different way of managing their .dll files in the newest versions.
This was thrown while attempting to install IPA on Beat Saber (oculus store version).

     Patching UnityEngine.dll... ERROR: Oops! This should not have happened.
     System.Exception: Could not find any entry type!
          at IPA.Patcher.PatchedModule.Patch()
          at IPA.Program.Install(PatchContext context)
     [Press any key to quit]

**Comment by russianGecko** [comment]
Solved.

**Comment by zhaoyh630MS** [comment]
How do you solve this?
