### ISSUE TITLE
Cannot mod game

### ISSUE THREAD

**Issue by NateKomodo** [Eusth/IPA#9]
Whenever i drag and drop a games executable onto IPA i get the following error:
```Updating files...
Architecture: x64
Successfully updated files!
Patching UnityEngine.dll... ERROR: Oops! This should not have happened.

System.Exception: Could not find any entry type!
   at IPA.Patcher.PatchedModule.Patch()
   at IPA.Program.Install(PatchContext context)

[Press any key to quit]
```
Any solutions?

**Comment by NateKomodo** [comment]
Solved, UnityEngine.dll in some builds from unity games is empty, changing the context to only be UnityEngine.Core.dll fixed the issue. You may want to add a check for if the DLL has types or not in it

**Comment by AlienPolygon** [comment]
> Solved, UnityEngine.dll in some builds from unity games is empty, changing the context to only be UnityEngine.Core.dll fixed the issue. You may want to add a check for if the DLL has types or not in it

I'm seeing the same error for honey select 2 studio neo v2, can you go into detail on what you changed?
